<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = array(
            array('id' => '1','name' => 'Aceite de oliva','category_product_id' => '1','measure_unit_id' => '2','conversion_factor' => '750.00','depletion_factor' => '0','purchase_value' => '5.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '2','name' => 'Aceite vegetal','category_product_id' => '1','measure_unit_id' => '2','conversion_factor' => '17000.00','depletion_factor' => '4','purchase_value' => '24.99','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '3','name' => 'Perejil seco','category_product_id' => '1','measure_unit_id' => '1','conversion_factor' => '56.70','depletion_factor' => '40','purchase_value' => '2.29','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '4','name' => 'Maiz  en lata','category_product_id' => '1','measure_unit_id' => '1','conversion_factor' => '4.32','depletion_factor' => '5','purchase_value' => '5.49','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '5','name' => 'Laurel','category_product_id' => '1','measure_unit_id' => '1','conversion_factor' => '53.00','depletion_factor' => '5','purchase_value' => '5.79','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '6','name' => 'Pimieta','category_product_id' => '1','measure_unit_id' => '1','conversion_factor' => '250.00','depletion_factor' => '0','purchase_value' => '0.50','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '7','name' => 'Azucar','category_product_id' => '1','measure_unit_id' => '1','conversion_factor' => '1000.00','depletion_factor' => '0','purchase_value' => '2.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '8','name' => 'Chocolate nutella','category_product_id' => '1','measure_unit_id' => '1','conversion_factor' => '751.00','depletion_factor' => '5','purchase_value' => '9.99','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '9','name' => 'Oregano','category_product_id' => '1','measure_unit_id' => '1','conversion_factor' => '250.00','depletion_factor' => '0','purchase_value' => '1.75','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '10','name' => 'Aceite de trufa','category_product_id' => '1','measure_unit_id' => '2','conversion_factor' => '250.00','depletion_factor' => '7','purchase_value' => '13.46','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '11','name' => 'Sal ','category_product_id' => '1','measure_unit_id' => '1','conversion_factor' => '737.00','depletion_factor' => '5','purchase_value' => '1.33','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '12','name' => 'Nueces','category_product_id' => '1','measure_unit_id' => '1','conversion_factor' => '907.00','depletion_factor' => '5','purchase_value' => '22.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '13','name' => 'Alcaparras','category_product_id' => '1','measure_unit_id' => '1','conversion_factor' => '350.00','depletion_factor' => '5','purchase_value' => '9.80','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '14','name' => 'Aceitunas negras','category_product_id' => '1','measure_unit_id' => '1','conversion_factor' => '185.00','depletion_factor' => '5','purchase_value' => '8.99','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '15','name' => 'Aceitunas verdes','category_product_id' => '1','measure_unit_id' => '1','conversion_factor' => '2250.00','depletion_factor' => '5','purchase_value' => '18.29','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '16','name' => 'Ketchup','category_product_id' => '14','measure_unit_id' => '1','conversion_factor' => '1.00','depletion_factor' => '5','purchase_value' => '5.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '17','name' => 'Mostaza dijon','category_product_id' => '14','measure_unit_id' => '1','conversion_factor' => '5000.00','depletion_factor' => '5','purchase_value' => '22.50','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '18','name' => 'Mayonesa','category_product_id' => '14','measure_unit_id' => '1','conversion_factor' => '4000.00','depletion_factor' => '0','purchase_value' => '20.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '19','name' => 'Vinagre balsámico','category_product_id' => '14','measure_unit_id' => '3','conversion_factor' => '128.00','depletion_factor' => '0','purchase_value' => '10.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '20','name' => 'Sodas','category_product_id' => '5','measure_unit_id' => '4','conversion_factor' => '12.00','depletion_factor' => '0','purchase_value' => '7.25','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '21','name' => 'Jugo de cranberries','category_product_id' => '5','measure_unit_id' => '4','conversion_factor' => '1.00','depletion_factor' => '0','purchase_value' => '0.50','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '22','name' => 'Agua spellegrino mineral','category_product_id' => '5','measure_unit_id' => '4','conversion_factor' => '12.00','depletion_factor' => '0','purchase_value' => '1.95','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '23','name' => 'Coca-cola','category_product_id' => '5','measure_unit_id' => '4','conversion_factor' => '36.00','depletion_factor' => '0','purchase_value' => '17.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '24','name' => 'Sprite','category_product_id' => '5','measure_unit_id' => '4','conversion_factor' => '12.00','depletion_factor' => '0','purchase_value' => '10.49','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '25','name' => 'Aislador de calor','category_product_id' => '3','measure_unit_id' => '4','conversion_factor' => '1.00','depletion_factor' => '0','purchase_value' => '1.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '26','name' => 'Kit desechable mb','category_product_id' => '3','measure_unit_id' => '4','conversion_factor' => '1.00','depletion_factor' => '0','purchase_value' => '1.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '27','name' => 'Bolsa  5x10','category_product_id' => '3','measure_unit_id' => '4','conversion_factor' => '1.00','depletion_factor' => '0','purchase_value' => '0.25','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '28','name' => 'Bolsa 11x15','category_product_id' => '3','measure_unit_id' => '4','conversion_factor' => '1.00','depletion_factor' => '0','purchase_value' => '0.30','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '29','name' => 'Bolsa 4x10','category_product_id' => '3','measure_unit_id' => '4','conversion_factor' => '1.00','depletion_factor' => '0','purchase_value' => '0.35','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '30','name' => 'Naranja ','category_product_id' => '8','measure_unit_id' => '1','conversion_factor' => '15.00','depletion_factor' => '10','purchase_value' => '1.50','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '31','name' => 'Limon','category_product_id' => '8','measure_unit_id' => '1','conversion_factor' => '366.00','depletion_factor' => '0','purchase_value' => '0.50','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '32','name' => 'Kiwi','category_product_id' => '8','measure_unit_id' => '1','conversion_factor' => '1.00','depletion_factor' => '2','purchase_value' => '0.40','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '33','name' => 'Uvas','category_product_id' => '8','measure_unit_id' => '1','conversion_factor' => '16.00','depletion_factor' => '12','purchase_value' => '6.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '34','name' => 'Melon','category_product_id' => '8','measure_unit_id' => '1','conversion_factor' => '1.00','depletion_factor' => '33','purchase_value' => '3.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '35','name' => 'Papaya','category_product_id' => '8','measure_unit_id' => '1','conversion_factor' => '1.00','depletion_factor' => '32','purchase_value' => '3.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '36','name' => 'Fresa','category_product_id' => '8','measure_unit_id' => '1','conversion_factor' => '16.00','depletion_factor' => '1','purchase_value' => '7.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '37','name' => 'Mango','category_product_id' => '8','measure_unit_id' => '1','conversion_factor' => '16.00','depletion_factor' => '0','purchase_value' => '3.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '38','name' => 'Piña','category_product_id' => '8','measure_unit_id' => '1','conversion_factor' => '1.00','depletion_factor' => '45','purchase_value' => '2.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '39','name' => 'Zumo de limón','category_product_id' => '8','measure_unit_id' => '2','conversion_factor' => '1500.00','depletion_factor' => '5','purchase_value' => '14.74','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '40','name' => 'Sandia','category_product_id' => '8','measure_unit_id' => '1','conversion_factor' => '1.00','depletion_factor' => '32','purchase_value' => '3.50','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '41','name' => 'Lentejas','category_product_id' => '2','measure_unit_id' => '1','conversion_factor' => '452.00','depletion_factor' => '0','purchase_value' => '1.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '42','name' => 'Arroz','category_product_id' => '2','measure_unit_id' => '1','conversion_factor' => '800.00','depletion_factor' => '2','purchase_value' => '21.10','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '43','name' => 'Porotos rojos','category_product_id' => '2','measure_unit_id' => '1','conversion_factor' => '452.00','depletion_factor' => '0','purchase_value' => '1.50','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '44','name' => 'Porotos blancos','category_product_id' => '2','measure_unit_id' => '1','conversion_factor' => '452.00','depletion_factor' => '0','purchase_value' => '10.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '45','name' => 'Crema de leche','category_product_id' => '9','measure_unit_id' => '2','conversion_factor' => '1100.00','depletion_factor' => '0','purchase_value' => '6.20','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '46','name' => 'Mantequilla','category_product_id' => '9','measure_unit_id' => '1','conversion_factor' => '1000.00','depletion_factor' => '0','purchase_value' => '1.30','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '47','name' => 'Huevos','category_product_id' => '9','measure_unit_id' => '4','conversion_factor' => '40.00','depletion_factor' => '10','purchase_value' => '9.69','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '48','name' => 'Queso de cabra','category_product_id' => '9','measure_unit_id' => '1','conversion_factor' => '1000.00','depletion_factor' => '5','purchase_value' => '14.99','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '49','name' => 'Leche liquida entera','category_product_id' => '9','measure_unit_id' => '2','conversion_factor' => '1000.00','depletion_factor' => '5','purchase_value' => '16.79','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '50','name' => 'Queso mozarella','category_product_id' => '9','measure_unit_id' => '1','conversion_factor' => '2500.00','depletion_factor' => '0','purchase_value' => '10.30','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '51','name' => 'Queso mozarella pedersen','category_product_id' => '9','measure_unit_id' => '1','conversion_factor' => '2300.00','depletion_factor' => '5','purchase_value' => '9.99','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '52','name' => 'Queso parmesano','category_product_id' => '9','measure_unit_id' => '1','conversion_factor' => '1130.00','depletion_factor' => '10','purchase_value' => '14.49','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '53','name' => 'Mascarpone riba smith','category_product_id' => '9','measure_unit_id' => '1','conversion_factor' => '226.00','depletion_factor' => '5','purchase_value' => '4.50','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '54','name' => 'Queso azul','category_product_id' => '9','measure_unit_id' => '1','conversion_factor' => '540.00','depletion_factor' => '5','purchase_value' => '8.39','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '55','name' => 'Queso parmesano maduro','category_product_id' => '9','measure_unit_id' => '1','conversion_factor' => '9000.00','depletion_factor' => '10','purchase_value' => '14.10','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '56','name' => 'Mozarella fresco','category_product_id' => '9','measure_unit_id' => '1','conversion_factor' => '453.00','depletion_factor' => '5','purchase_value' => '6.49','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '57','name' => 'Vino pino grillo','category_product_id' => '4','measure_unit_id' => '2','conversion_factor' => '750.00','depletion_factor' => '5','purchase_value' => '8.55','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '58','name' => 'Ginebra ','category_product_id' => '4','measure_unit_id' => '2','conversion_factor' => '750.00','depletion_factor' => '0','purchase_value' => '12.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '59','name' => 'Triple sec','category_product_id' => '4','measure_unit_id' => '2','conversion_factor' => '750.00','depletion_factor' => '0','purchase_value' => '18.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '60','name' => 'Vodka absolut','category_product_id' => '4','measure_unit_id' => '2','conversion_factor' => '750.00','depletion_factor' => '5','purchase_value' => '20.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '61','name' => 'Seco','category_product_id' => '4','measure_unit_id' => '2','conversion_factor' => '5000.00','depletion_factor' => '0','purchase_value' => '9.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '62','name' => 'Vino closs','category_product_id' => '4','measure_unit_id' => '2','conversion_factor' => '3000.00','depletion_factor' => '5','purchase_value' => '8.29','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '63','name' => 'Ron abuelo','category_product_id' => '4','measure_unit_id' => '2','conversion_factor' => '700.00','depletion_factor' => '0','purchase_value' => '9.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '64','name' => 'Tequila','category_product_id' => '4','measure_unit_id' => '2','conversion_factor' => '800.00','depletion_factor' => '0','purchase_value' => '10.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '65','name' => 'Harina','category_product_id' => '6','measure_unit_id' => '1','conversion_factor' => '50000.00','depletion_factor' => '5','purchase_value' => '39.75','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '66','name' => 'Levadura','category_product_id' => '6','measure_unit_id' => '1','conversion_factor' => '435.00','depletion_factor' => '5','purchase_value' => '12.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '67','name' => 'Pan vital','category_product_id' => '6','measure_unit_id' => '4','conversion_factor' => '14.00','depletion_factor' => '0','purchase_value' => '6000.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '68','name' => 'Farfalle','category_product_id' => '11','measure_unit_id' => '1','conversion_factor' => '500.00','depletion_factor' => '0','purchase_value' => '1.66','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '69','name' => 'Penne','category_product_id' => '11','measure_unit_id' => '1','conversion_factor' => '500.00','depletion_factor' => '0','purchase_value' => '1.08','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '70','name' => 'Tagliattelle','category_product_id' => '11','measure_unit_id' => '1','conversion_factor' => '500.00','depletion_factor' => '0','purchase_value' => '1.74','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '71','name' => 'Spaghetti','category_product_id' => '11','measure_unit_id' => '1','conversion_factor' => '500.00','depletion_factor' => '0','purchase_value' => '1.08','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '72','name' => 'Spaghetti integral','category_product_id' => '11','measure_unit_id' => '1','conversion_factor' => '500.00','depletion_factor' => '0','purchase_value' => '2.20','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '73','name' => 'Fettuccine','category_product_id' => '11','measure_unit_id' => '1','conversion_factor' => '500.00','depletion_factor' => '0','purchase_value' => '1.74','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '74','name' => 'Lasagne','category_product_id' => '11','measure_unit_id' => '1','conversion_factor' => '500.00','depletion_factor' => '0','purchase_value' => '2.25','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '75','name' => 'Bacon','category_product_id' => '12','measure_unit_id' => '3','conversion_factor' => '240.00','depletion_factor' => '41','purchase_value' => '58.32','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '76','name' => 'Peperonni pieza','category_product_id' => '12','measure_unit_id' => '1','conversion_factor' => '1000.00','depletion_factor' => '15','purchase_value' => '13.91','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '77','name' => 'Carne molida','category_product_id' => '12','measure_unit_id' => '1','conversion_factor' => '1000.00','depletion_factor' => '0','purchase_value' => '7.59','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '78','name' => 'Filete de pollo','category_product_id' => '12','measure_unit_id' => '1','conversion_factor' => '1000.00','depletion_factor' => '0','purchase_value' => '3.20','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '79','name' => 'Entraña','category_product_id' => '12','measure_unit_id' => '1','conversion_factor' => '1000.00','depletion_factor' => '40','purchase_value' => '27.55','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '80','name' => 'Filete de res','category_product_id' => '12','measure_unit_id' => '1','conversion_factor' => '1000.00','depletion_factor' => '35','purchase_value' => '16.53','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '81','name' => 'Salmon ahumado','category_product_id' => '12','measure_unit_id' => '1','conversion_factor' => '227.00','depletion_factor' => '0','purchase_value' => '10.99','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '82','name' => 'Anchoas ','category_product_id' => '12','measure_unit_id' => '1','conversion_factor' => '396.00','depletion_factor' => '0','purchase_value' => '9.99','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '83','name' => 'Prosciutto','category_product_id' => '12','measure_unit_id' => '1','conversion_factor' => '1000.00','depletion_factor' => '0','purchase_value' => '19.40','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '84','name' => 'Arañita','category_product_id' => '12','measure_unit_id' => '1','conversion_factor' => '450.00','depletion_factor' => '0','purchase_value' => '4.25','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '85','name' => 'Tubo de calamar','category_product_id' => '12','measure_unit_id' => '1','conversion_factor' => '450.00','depletion_factor' => '0','purchase_value' => '5.00','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL),
            array('id' => '86','name' => 'Camarones','category_product_id' => '12','measure_unit_id' => '1','conversion_factor' => '400.00','depletion_factor' => '30','purchase_value' => '6.50','stock_quantity' => '0','min_quantity' => '0','max_quantity' => '0','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'deleted_at' => NULL)
          );

          App\Product::insert($products);
    }
}
